@startuml
participant client
participant connect
participant logic
participant business

client -> connect: tcp监听后调用SignIn
connect -> logic: ConnSignIn
logic -> business: Auth(鉴权)
business -> business: 检查token是否合法

business -> logic: 返回登录结果
logic -> connect: 返回登录结果
logic --> logic: 登录成功就更新DB中的设备信息

connect -> client: 给client返回登录结果

connect --> connect: 登录成功在connect服务中保存conn实例
@enduml
